### ISSUE TITLE
Undefined method strip after updating to 0.17.1

### ISSUE THREAD

**Issue by emilianodellacasa** [zold-io/zold#589]
After updating to version 0.17.1, many logs appeared like the following one:

78.26.142.131:4096: undefined method `strip' for nil:NilClass in 1.65s

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#589](https://github.com/zold-io/zold/issues/589) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by yegor256** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zold-io/zold/issues/589#issuecomment-443121021))

@yegor256 The job [#589](https://github.com/zold-io/zold/issues/589) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/821d08a5-e4d8-4257-a742-a2602d5ebf04); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.2`

**Comment by yegor256** [comment]
@emilianodellacasa it's fixed, thanks
